type FBSong {
    id: String!
    title: String
    chordChart: String
    composer: FBComposer
}

input FBSongCreateInput {
    title: String
    composer: String
    chordChart: String
}

input FBSongUpdateInput {
    id: String!
    title: String
    composer: String
    chordChart: String
}

type FakeBookSongResponse implements FakeBookResponse {
  code: String!
  success: Boolean!
  message: String!
  song: FBSong
}

extend type Query {
  getSong(id: String!): FBSong
}

extend type Mutation {
    createSong(song: FBSongCreateInput): FakeBookSongResponse
    updateSong(song: FBSongUpdateInput): FakeBookSongResponse
}