

type FBSong {
    id: String
    title: String
    chordChart: String
    composer: FBComposer
    key: String
    year: String
    style: String
}

type FakeBookSongResponse implements FakeBookResponse {
  code: String!
  success: Boolean!
  message: String!
  song: FBSong
}
