type FBSong {
    id: String!
    title: String
    chordChart: String
    composer: FBComposer
    key: String
    year: String
    style: String
}

input FBSongCreateInput {
    title: String
    composer: String
    chordChart: String
    key: String
    year: String
    style: String
}

input FBSongUpdateInput {
    id: String!
    title: String
    composer: String
    chordChart: String
    key: String
    year: String
    style: String
}

type FakeBookSongResponse implements FakeBookResponse {
  code: String!
  success: Boolean!
  message: String!
  song: FBSong
}

extend type Query {
  getSong(id: String!): FBSong
}