interface FakeBookResponse {
  code: String!
  success: Boolean!
  message: String!
}

type Mutation {
    createSong(song: FBSongCreateInput): FakeBookSongResponse
    updateSong(song: FBSongUpdateInput): FakeBookSongResponse
}