service: jazz-charts-api

plugins:
  - serverless-offline
  - serverless-wsgi

provider:
  name: aws
  runtime: python3
  stage: ${opt:stage, 'dev'}
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource:
  #       - { "Fn::GetAtt": ["jazz-charts-table", "Arn" ] }
  environment:
    STAGE: ${self:provider.stage}

custom:
  wsgi:
    app: app.app

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

# resources:
#   Resources:
#     jazz-charts-table:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: jazz-charts-${self:provider.stage}
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#           - AttributeName: skey
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#           - AttributeName: skey
#             KeyType: RANGE
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1

