type FBComposer {
    id: String
    songs: [FBSong]
    fullName: String
}

input FBComposerCreateInput {
    songs: [String]
    fullName: String!
}

input FBComposerUpdateInput {
    id: String!
    songs: [String]
    fullName: String
}

type FakeBookComposerResponse implements FakeBookResponse {
  code: String!
  success: Boolean!
  message: String!
  composer: FBComposer
}

extend type Query {
  getComposer(id: String!): FBComposer
  getComposers(last_evaluated_key: String): [FBComposer]

}

extend type Mutation {
    createComposer(composer: FBComposerCreateInput): FakeBookComposerResponse
    updateComposer(composer: FBComposerUpdateInput): FakeBookComposerResponse
}