type FBComposer {
    id: String
    songs: [FBSong]
    name: String
}

type FakeBookComposerResponse implements FakeBookResponse {
  code: String!
  success: Boolean!
  message: String!
  composer: FBComposer
}

extend type Query {
  getComposer(id: String!): FBComposer
}